name: Manual Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: 'manual'
        type: string

jobs:
  build-extension:
    name: Build Extension
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: |
        npm run typecheck
        npm run lint
        npm run format:check
        npm test

    - name: Build extension
      run: npm run build

    - name: Create build zip
      run: |
        cd dist
        zip -r ../vega-extension-${{ inputs.version }}-$(date +%Y%m%d-%H%M%S).zip .
        cd ..

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: vega-extension-${{ inputs.version }}-build
        path: vega-extension-*.zip
        retention-days: 30
