name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build extension
      run: npm run build

    - name: Create release zip
      run: |
        cd dist
        zip -r ../vega-ai-job-capture-${{ github.ref_name }}.zip .
        cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: vega-ai-job-capture-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## Vega AI Job Capture Extension - ${{ github.ref_name }}

          ### 📦 Downloads
          - **Chrome/Edge Extension**: `vega-ai-job-capture-${{ github.ref_name }}.zip`

          ### 🚀 Installation Options

          #### Option 1: Self-Hosted (Recommended for developers)
          1. Download and extract `vega-ai-job-capture-${{ github.ref_name }}.zip`
          2. Run your own backend server at `http://localhost:8765`
          3. Open Chrome/Edge and navigate to `chrome://extensions/` or `edge://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder

          #### Option 2: Chrome/Edge Web Store (Coming Soon)
          - Install directly from the web store
          - Configure your own API host in the extension settings
          - No backend setup required if you have a hosted instance

          ### ⚙️ Configuration
          - **Default API Host**: `http://localhost:8765`
          - **Custom Host**: Can be configured in extension settings (marketplace version)

          ### 📋 Requirements
          - Chrome 88+ or Edge 88+
          - Backend API server (for self-hosted setup)

          ### 🆕 What's Changed

          See the auto-generated release notes below for detailed changes.
